name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - run: rm .gitignore # Commit build files
    - run: | # node modules was too big to commit
        touch .gitignore
        echo "node_modules" >> .gitignore

    - uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: build # The branch the action should deploy to.
        folder: . # The folder the action should deploy.
