name: Formatting and Testing

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  check:
    name: "Check Formatting and Linting"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: npm ci

      - name: Format Check
        run: npm run format:prettier:check

      - name: Lint Check
        run: npm run format:lint:check

    