name: Deploy to Vultr

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master

jobs:
  deploy:
    name: "Deploy to Vultr"
    runs-on: ubuntu-latest
    environment: production
    env:
      TF_VAR_DB_PASSWORD: ${{ secrets.TF_VAR_DB_PASSWORD }}
      TF_VAR_DB_USER: ${{ secrets.TF_VAR_DB_USER }}
      TF_VAR_EMAIL_NAME: ${{ secrets.TF_VAR_EMAIL_NAME }}
      TF_VAR_EMAIL_PASSWORD: ${{ secrets.TF_VAR_EMAIL_PASSWORD }}
      TF_VAR_VULTR_API_KEY: ${{ secrets.TF_VAR_VULTR_API_KEY }}
      TF_VAR_REPOSITORY_URL: ${{ github.repositoryUrl }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        working-directory: terraform
