name: Deploy to Vultr

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        env:
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}

      - name: Terraform Plan
        run: terraform plan
        env:
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}